# SPDX-License-Identifier: GPL-3.0-or-later
# TooTalk postfix + opendkim supervisor 통합 entry.
# 한글 주석: postfix 의 init-style daemon 2개 의 foreground supervise.

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:postfix]
command=/usr/sbin/postfix start-fg
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:opendkim]
command=/usr/sbin/opendkim -f -x /etc/opendkim.conf
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
